apiVersion: v1
kind: Service
metadata:
  annotations:
      prometheus.io/scrape: 'true'      
      prometheus.io/path: '/metrics/prometheus/'
      prometheus.io/port: '4040'
  name: {{ include "spark-thrift-server.fullname" . }}-driver
  labels:
    {{- include "spark-thrift-server.labels" . | nindent 4 }}
spec:
  ports:
  - name: spark-ui
    port: 4040
    protocol: TCP
    targetPort: 4040
  - name: spark-thrift
    port: 10000
    protocol: TCP
    targetPort: 10000
  - name: jdbc-port
    port: 10016
    protocol: TCP
    targetPort: 10016
{{- if .Values.historyserver.enabled }}
  - name: history-port
    port: 18080
    protocol: TCP
    targetPort: 18080
{{- end }}
  selector:
    app: {{ include "spark-thrift-server.fullname" . }}-driver
