apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "spark-thrift-server.fullname" . }}-metastore
spec:
  replicas: {{ .Values.metastore.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "spark-thrift-server.fullname" . }}-metastore
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "spark-thrift-server.fullname" . }}-metastore
    spec:
      serviceAccountName: {{ include "spark-thrift-server.serviceAccountName" . }}
      serviceAccount: {{ include "spark-thrift-server.serviceAccountName" . }}
      {{- with .Values.metastore.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}        
      {{- with .Values.metastore.nodeSelector }}      
      nodeSelector:
        {{ toYaml . | indent 6 }}
      {{- end }}    
      {{- with .Values.metastore.tolerations }}
      tolerations:
        {{- toYaml . | nindent 6 }}
      {{- end }}      
      containers:
      - name: metastore
        image: "{{ .Values.metastore.image.repository }}:{{ .Values.metastore.image.tag }}"
        imagePullPolicy: {{ .Values.metastore.image.pullPolicy }}
        # post start script to copy secret file to the correct folder.  (K8s secret mount replace all files in a folder)        
        resources:
        {{- toYaml .Values.metastore.resources | nindent 10 }}
        {{- if .Values.metastore.includeKeyAndSecret }}          
        {{- with .Values.metastore.env }}
        env:
        {{- toYaml . | nindent 10 }} 
        {{- end }}
        {{- end }}          
        lifecycle:
          postStart:
            exec:
              command:
                - /bin/sh
                - -c
                - cp /opt/tempconfig/metastoreconf/metastore-site.xml /opt/hive-metastore/conf/metastore-site.xml&&cp /opt/tempconfig/siteconifg/core-site.xml /opt/hadoop/etc/hadoop/core-site.xml
        ports:
        - containerPort: 9083
        command: ["/opt/hive-metastore/bin/start-metastore"]
        args: ["-p", "9083"]        
        volumeMounts:
        # mount secret to a tempconfig folder.  Secret mounting will replace file in folder
        - mountPath:  /opt/tempconfig/metastoreconf
          name:  metastore-site-secret
        - mountPath:  /opt/tempconfig/siteconifg
          name: core-site-secret
      volumes:
        - name: core-site-secret
          secret:
           secretName: {{ .Values.metastore.coreSiteSecret }}
           items:
            - key: core-site.xml
              path: core-site.xml
        - name: metastore-site-secret
          secret:
            secretName: {{ .Values.metastore.metastoreSiteSecret }}
            items:
              - key: metastore-site.xml
                path: metastore-site.xml