{{- if .Values.metastore.initSchema.enabled -}}
kind: Job
apiVersion: batch/v1
metadata:
  name: {{ include "spark-thrift-server.fullname" . }}-metastore-initschema
spec:
  template:
    spec:
      {{- with .Values.metastore.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
      initContainers:
        - name: wait-for-postgres
          image: "{{ .Values.metastore.busyboxImage.repository }}:{{ .Values.metastore.busyboxImage.tag }}"
          command:
            - /bin/sh
            - '-c'
            - >-
              until nc -zv {{ .Values.metastore.initSchema.dbHost }} {{ .Values.metastore.initSchema.dbPort }} -w1; do echo 'waiting for db'; sleep 1;
              done       
      containers:
        - name: hivemeta
          image: "{{ .Values.metastore.image.repository }}:{{ .Values.metastore.image.tag }}"
          {{- with .Values.metastore.initSchema.env }}
          env:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.metastore.image.pullPolicy }}
          command: ["sh", "-c", "/opt/hive-metastore/bin/schematool --verbose -initSchema -dbType postgres -userName {{ .Values.metastore.initSchema.userName }} -passWord $(DB_PASSWORD) -url jdbc:postgresql://{{ .Values.metastore.initSchema.dbHost }}:{{ .Values.metastore.initSchema.dbPort }}/metastore_db?useSSL=false ||true"]          
      restartPolicy: Never
  backoffLimit: 1
{{- end -}}  