apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-thrift-server.fullname" . }}-metastore  
spec:
  ports:
  - port: 9083
  selector:
    app: {{ include "spark-thrift-server.fullname" . }}-metastore