apiVersion: v1
kind: Service
metadata:
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path: '/metrics/executors/prometheus/'      
      prometheus.io/port: '4040'
  name: {{ include "spark-thrift-server.fullname" . }}-driver-headless
  labels:
    {{- include "spark-thrift-server.labels" . | nindent 4 }}
spec:
  ports:
  - name: driver-rpc-port
    protocol: TCP
    port: 7078
    targetPort: 7078
  - name: blockmanager
    protocol: TCP
    port: 7079
    targetPort: 7079    
  clusterIP: None
  selector:
    app: {{ include "spark-thrift-server.fullname" . }}-driver
